global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /opt/bstg/etc/prometheus.rules

scrape_configs:
  - job_name: prometheus
    target_groups:
      - targets:
        - prod.example.org:9090

  - job_name: node
    target_groups:
      - targets:
        - prod.example.org:9100

  - job_name: alertmanager
    target_groups:
      - targets:
        - prod.example.org:9093

  - job_name: pushgateway
    target_groups:
      - targets:
        - prod.example.org:9091
